version: '2'

networks:
  hostnet:
    external: true

volumes:
  esdata:
    driver: local

services:
  
  fluentd:
    build: .
    volumes: 
      - "./fluent_logs:/fluentd/log"
      - "./fluent.conf:/fluentd/etc/fluent.conf"
    networks:
      hostnet:
        ipv4_address: 172.18.0.10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - hostnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    ports:
      - "5601:5601"
    networks:
      - hostnet

  metricbeat:
    build: ./metricbeat
    image: mbeat
    env_file:
      - /var/icoworld/.metricbeat.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./metricbeat/metricbeat.yml:/metricbeat/metricbeat.yml"
      - "./metricbeat/system.yml:/metricbeat/modules.d/system.yml"
      - "./metricbeat/nginx.yml:/metricbeat/modules.d/nginx.yml"
      - "/proc:/hostfs/proc"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/:/hostfs:ro"
    networks:
      - hostnet
    external_links:
      - database
