version: '2'

volumes:
  fluent_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/fluent_logs'

networks:
  fluentd:
    external: true

services:
  fluentd:
    build: .
    volumes: 
      - "fluent_logs:/fluentd/log"
      - "./fluent.conf:/fluentd/etc/fluent.conf"
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      fluentd:
        aliases:
          - fluentd.fluentd

  elasticsearch:
    image: elasticsearch
    expose: 
      - 9200
    ports:
      - "9200:9200"
    networks:
      - fluentd

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - fluentd
