version: '2'

networks:
  fluentd:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  fluentd:
    build: .
    volumes: 
      - "./fluent_logs:/fluentd/log"
      - "./fluent.conf:/fluentd/etc/fluent.conf"
    networks:
      fluentd:
        ipv4_address: 172.30.0.10

  elasticsearch:
    image: elasticsearch
    networks:
      - fluentd

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    networks:
      - fluentd

  metricbeat:
    build: ./metricbeat
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - fluentd
