---
metricbeat.config.modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.modules:
  - 
    module: Docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - image
      - info
      - memory
      - network
    enabled: true    
    hosts: ["unix:///var/run/docker.sock"]
    period: 5s
output.elasticsearch: 
  hosts: 
      - "elasticsearch:9200"
setup.kibana: 
  host: "kibana:5601"
