# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.4/metricbeat-module-nginx.html

- module: nginx
  metricsets:
    - stubstatus
  period: 10s

  # Nginx hosts
  hosts: ["http://172.30.0.112:8080"]

  # Path to server status. Default server-status
  server_status_path: "server-status"

  #username: "user"
  #password: "secret"
