version : "2"

networks:
  efk_fluentd:
    external: true

services:
  www:
    build: .
    image: nginx/log
    ports:
      - "9090:8080"
    volumes:
      - /var/jenkins/buildlog:/usr/share/nginx/www/logs
    container_name: listoflog
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 172.30.0.10:24224
        tag: nginx
    networks:
      - efk_fluentd
